import streamlit as st
from PIL import Image
st.set_page_config(page_title='Chicken', page_icon=":chicken:", layout= 'wide')
st.logo(Image.open('Chicken.png'))
st.header('Welcome to')
st.subheader(':rainbow[**The Chicken Empire**]')
st.subheader('_website_')
st.divider()
st.subheader('Recent News:')
st.text('Making Chicken Empire website...')
st.divider()
st.subheader('About Me')
st.text('Hi im a youtuber who likes coding\nwe all have dreams\nand If you Subscribe\nyou would be helping\nme fulfil mine\nplease\n\/\/\/') 
st.link_button('Click Here Plz', 'https://www.youtube.com/@Join_The_Chicken_Empire/featured')
st.divider()
st.subheader('My Subscribers')
st.text('Smakshi Sarvaria\nZxJoshua33\nAmy Cartwright\nBayu Trikurnia\nEduardo Díaz\nzian asher\nyvette metzger\nContry balls\nsheuli bhowmik\nEster Nakale\nHanan Alwaqet\nTấn Hà Thị\nKing Nathan\nTeremoana Eli\nEric Hernán Herazo Barrios\nMuseum\nSoshjackhe hello 120')
st.divider()
st.subheader('Wonderful portraits:')
st.image(Image.open('CE Poster (Portrait).png'), width=400)
st.text('Credits: By Zxjoshua33(My Friend)')
st.image(Image.open('James.png'), width=400)
st.text('Credits: By OppositeAce8412(My Friend)')
st.image(Image.open('Standard.png'), width=400) 
st.text('Credits: By Zxjoshua33(My Friend)')
st.image(Image.open('James1.png'), width=400) 
st.text('Credits: By OppositeAce8412(My Friend)')
st.image(Image.open('Chick (1).png'), width=400)
st.text('Credits: By Me')
st.image(Image.open('Chicks.png'), width=400)
st.text('Credits: By Me')
st.image(Image.open('The Chicken Empire.png'), width=400)
st.text('Credits: By Me')
st.image(Image.open('Burn.png'), width=400)
st.text('Credits: By Me')
st.image(Image.open('Mew.png'), width=400)
st.text('Credits: By Me')
st.image(Image.open('Rock.png'), width=400)
st.text('Credits: By Me')
st.image(Image.open('Roost.png'), width=400)
st.text('Credits: By Me')
st.divider()
st.subheader('Credits')
st.text('Donnie(My other friend)\nZxJoshua33(You should go see his channel)\nOppositeAce8412(You should go see his channel)\nChickens\n')