import streamlit as st
from PIL import Image
st.set_page_config(page_title='Chicken Empire Comic', page_icon=":chicken:", layout= 'wide')
st.logo(Image.open('Chicken.png'))
st.image(Image.open('1.png'))
st.image(Image.open('2.png'))
st.image(Image.open('3.png'))
st.image(Image.open('4.png'))
st.image(Image.open('5.png'))
st.image(Image.open('6.png'))
st.image(Image.open('7.png'))
st.image(Image.open('8.png'))
st.image(Image.open('9.png'))
st.image(Image.open('10.png'))
st.image(Image.open('11.png'))
st.image(Image.open('12.png'))
st.image(Image.open('13.png'))
st.image(Image.open('14.png'))
st.image(Image.open('15.png'))
st.image(Image.open('16.png'))
st.image(Image.open('17.png'))
st.image(Image.open('18.png'))
st.image(Image.open('19.png'))
st.image(Image.open('20.png'))
st.image(Image.open('21.png'))
st.image(Image.open('22.png'))
st.image(Image.open('23.png'))
st.image(Image.open('24.png'))
st.image(Image.open('25.png'))
st.image(Image.open('26.png'))
st.image(Image.open('27.png'))
st.image(Image.open('28.png'))
st.image(Image.open('29.png'))