import streamlit as st
from PIL import Image
st.set_page_config(page_title='Chicken Empire Comic', page_icon=":chicken:", layout= 'wide')
st.logo(Image.open('Chicken.png'))
with st.sidebar:
    st.link_button('Back to home', 'https://thechickenempire.streamlit.app/')
st.image(Image.open('1.png'), width=500)
st.image(Image.open('2.png'), width=500)
st.image(Image.open('3.png'), width=500)
st.image(Image.open('4.png'), width=500)
st.image(Image.open('5.png'), width=500)
st.image(Image.open('6.png'), width=500)
st.image(Image.open('7.png'), width=500)
st.image(Image.open('8.png'), width=500)
st.image(Image.open('9.png'), width=500)
st.image(Image.open('10.png'), width=500)
st.image(Image.open('11.png'), width=500)
st.image(Image.open('12.png'), width=500)
st.image(Image.open('13.png'), width=500)
st.image(Image.open('14.png'), width=500)
st.image(Image.open('15.png'), width=500)
st.image(Image.open('16.png'), width=500)
st.image(Image.open('17.png'), width=500)
st.image(Image.open('18.png'), width=500)
st.image(Image.open('19.png'), width=500)
st.image(Image.open('20.png'), width=500)
st.image(Image.open('21.png'), width=500)
st.image(Image.open('22.png'), width=500)
st.image(Image.open('23.png'), width=500)
st.image(Image.open('24.png'), width=500)
st.image(Image.open('25.png'), width=500)
st.image(Image.open('26.png'), width=500)
st.image(Image.open('27.png'), width=500)
st.image(Image.open('28.png'), width=500)
st.image(Image.open('29.png'), width=500)
st.image(Image.open('30.png'), width=500)
st.image(Image.open('31.png'), width=500)
st.image(Image.open('32.png'), width=500)
st.image(Image.open('33.png'), width=500)
st.image(Image.open('34.png'), width=500)
st.image(Image.open('35.png'), width=500)
st.image(Image.open('36.png'), width=500)
st.image(Image.open('37.png'), width=500)
st.image(Image.open('38.png'), width=500)
st.image(Image.open('39.png'), width=500)
st.image(Image.open('40.png'), width=500)
st.image(Image.open('41.png'), width=500)
st.image(Image.open('42.png'), width=500)
st.image(Image.open('43.png'), width=500)
st.image(Image.open('44.png'), width=500)
st.image(Image.open('45.png'), width=500)
st.image(Image.open('46.png'), width=500)
st.image(Image.open('47.png'), width=500)
st.image(Image.open('48.png'), width=500)
st.image(Image.open('49.png'), width=500)
st.image(Image.open('50.png'), width=500)
st.image(Image.open('51.png'), width=500)
st.image(Image.open('52.png'), width=500)
st.divider()
st.subheader('Credits:')
st.text('Oscar\nDonnie\nEthan\nMe')